name: JourneysEndFarlands
version: 1.0.0
main: project.kompass.journeysEndFarlands.JourneysEndFarlands
api-version: '1.21'
load: STARTUP
description: Generates the classic Farlands at the world border.